DROP TABLE IF EXISTS table_include_all_types;

CREATE TABLE table_include_all_types
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    nav_byte TINYINT,
    nav_short SMALLINT,
    nav_integer INTEGER,
    nav_long BIGINT,
    nav_float FLOAT,
    nav_double DOUBLE,
    nav_bollean BOOLEAN,
    nav_char CHAR,
    obj_byte TINYINT,
    obj_short SMALLINT,
    obj_integer INTEGER,
    obj_long BIGINT,
    obj_float FLOAT,
    obj_double DOUBLE,
    obj_bollean BOOLEAN,
    obj_char CHAR,
    obj_string VARCHAR(100),
    obj_big_decimal DECIMAL(100,2),
    obj_big_integer DECIMAL,
    nav_bytes VARBINARY(100),
    obj_bytes VARBINARY(100),
    obj_date TIMESTAMP,
    PRIMARY KEY (id)
);