DROP TABLE IF EXISTS table_include_all_types;

CREATE TABLE table_include_all_types
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    uid INTEGER,
    content BLOB(1000),
    PRIMARY KEY (id)
);