/*
 * Copyright 2014 mango.jfaster.org
 *
 * The Mango Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package org.jfaster.mango.crud.buildin.builder;

import java.util.ArrayList;
import java.util.List;

/**
 * @author ash
 */
public class BuildinUpdateBuilder extends AbstractBuildinBuilder {

  private final static String SQL_TEMPLATE = "update #table set %s where %s";

  // 使用 @ID 修饰的类属性
  private final String property4Id;

  // 使用 @ID 修饰的类属性对应的数据库列
  private final String column4Id;

  private final List<String> properties ;

  private final List<String> columns ;

  public BuildinUpdateBuilder(
          String property4Id, String property4AutoGenerated,
          List<String> props, List<String> cols) {

    properties = new ArrayList<String>(props); // 深拷贝
    columns = new ArrayList<String>(cols); // 深拷贝

    this.property4Id = property4Id;
    int index = properties.indexOf(property4Id);
    if (index < 0) {
      throw new IllegalArgumentException("error property4Id [" + property4Id + "]");
    }
    column4Id = columns.remove(index);
    properties.remove(index);

    if (property4AutoGenerated != null // 数据库自增
            && !property4Id.equals(property4AutoGenerated)) {
      index = properties.indexOf(property4AutoGenerated);
      if (index < 0) {
        throw new IllegalArgumentException("error property4AutoGenerated [" + property4AutoGenerated + "]");
      }
      properties.remove(index);
      columns.remove(index);
    }
  }

  @Override
  public String buildSql() {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < properties.size(); i++) {
      String prop = ":" + properties.get(i);
      String col = columns.get(i);
      sb.append(String.format("#if (%s != null) %s = %s,#end ", prop, col, prop));
    }
    sb.append("#trim_comma");
    String str = column4Id + " = :" + property4Id;
    return String.format(SQL_TEMPLATE, sb.toString(), str);
  }

}
