/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
package org.jfaster.mango.parser;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRootNode node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTInsert node, Object data);
  public Object visit(ASTDelete node, Object data);
  public Object visit(ASTUpdate node, Object data);
  public Object visit(ASTSelect node, Object data);
  public Object visit(ASTReplace node, Object data);
  public Object visit(ASTMerge node, Object data);
  public Object visit(ASTTruncate node, Object data);
  public Object visit(ASTJDBCParameter node, Object data);
  public Object visit(ASTJDBCIterableParameter node, Object data);
  public Object visit(ASTGlobalTable node, Object data);
  public Object visit(ASTJoinParameter node, Object data);
  public Object visit(ASTQuoteText node, Object data);
  public Object visit(ASTText node, Object data);
  public Object visit(ASTBlank node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTElseStatement node, Object data);
  public Object visit(ASTElseIfStatement node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTOrNode node, Object data);
  public Object visit(ASTAndNode node, Object data);
  public Object visit(ASTLTNode node, Object data);
  public Object visit(ASTGTNode node, Object data);
  public Object visit(ASTLENode node, Object data);
  public Object visit(ASTGENode node, Object data);
  public Object visit(ASTEQNode node, Object data);
  public Object visit(ASTNENode node, Object data);
  public Object visit(ASTNotNode node, Object data);
  public Object visit(ASTExpressionParameter node, Object data);
  public Object visit(ASTIntegerLiteral node, Object data);
  public Object visit(ASTStringLiteral node, Object data);
  public Object visit(ASTTrue node, Object data);
  public Object visit(ASTFalse node, Object data);
  public Object visit(ASTNull node, Object data);
}
/* JavaCC - OriginalChecksum=b1b913ab5be61b4b0408f2c2299322de (do not edit this line) */
