/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
package org.jfaster.mango.parser;

import org.jfaster.mango.parser.node.*;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRootNode node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTJDBCParameter node, Object data);
  public Object visit(ASTJDBCIterableParameter node, Object data);
  public Object visit(ASTGlobalTable node, Object data);
  public Object visit(ASTJoinParameter node, Object data);
  public Object visit(ASTText node, Object data);
  public Object visit(ASTBlank node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTElseStatement node, Object data);
  public Object visit(ASTElseIfStatement node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTOrNode node, Object data);
  public Object visit(ASTAndNode node, Object data);
  public Object visit(ASTLTNode node, Object data);
  public Object visit(ASTGTNode node, Object data);
  public Object visit(ASTLENode node, Object data);
  public Object visit(ASTGENode node, Object data);
  public Object visit(ASTEQNode node, Object data);
  public Object visit(ASTNENode node, Object data);
  public Object visit(ASTNotNode node, Object data);
  public Object visit(ASTExpressionParameter node, Object data);
  public Object visit(ASTIntegerLiteral node, Object data);
  public Object visit(ASTTrue node, Object data);
  public Object visit(ASTFalse node, Object data);
  public Object visit(ASTNull node, Object data);
}
/* JavaCC - OriginalChecksum=2a37bb6c25fa073aa05d8683207ed8b9 (do not edit this line) */
