/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package org.jfaster.mango.parser;

public interface ParserTreeConstants
{
  public int JJTROOTNODE = 0;
  public int JJTBLOCK = 1;
  public int JJTVOID = 2;
  public int JJTINSERT = 3;
  public int JJTDELETE = 4;
  public int JJTUPDATE = 5;
  public int JJTSELECT = 6;
  public int JJTREPLACE = 7;
  public int JJTMERGE = 8;
  public int JJTTRUNCATE = 9;
  public int JJTJDBCPARAMETER = 10;
  public int JJTJDBCITERABLEPARAMETER = 11;
  public int JJTGLOBALTABLE = 12;
  public int JJTJOINPARAMETER = 13;
  public int JJTQUOTETEXT = 14;
  public int JJTTEXT = 15;
  public int JJTBLANK = 16;
  public int JJTIFSTATEMENT = 17;
  public int JJTELSESTATEMENT = 18;
  public int JJTELSEIFSTATEMENT = 19;
  public int JJTEXPRESSION = 20;
  public int JJTORNODE = 21;
  public int JJTANDNODE = 22;
  public int JJTLTNODE = 23;
  public int JJTGTNODE = 24;
  public int JJTLENODE = 25;
  public int JJTGENODE = 26;
  public int JJTEQNODE = 27;
  public int JJTNENODE = 28;
  public int JJTNOTNODE = 29;
  public int JJTEXPRESSIONPARAMETER = 30;
  public int JJTINTEGERLITERAL = 31;
  public int JJTSTRINGLITERAL = 32;
  public int JJTTRUE = 33;
  public int JJTFALSE = 34;
  public int JJTNULL = 35;


  public String[] jjtNodeName = {
    "RootNode",
    "Block",
    "void",
    "Insert",
    "Delete",
    "Update",
    "Select",
    "Replace",
    "Merge",
    "Truncate",
    "JDBCParameter",
    "JDBCIterableParameter",
    "GlobalTable",
    "JoinParameter",
    "QuoteText",
    "Text",
    "Blank",
    "IfStatement",
    "ElseStatement",
    "ElseIfStatement",
    "Expression",
    "OrNode",
    "AndNode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "EQNode",
    "NENode",
    "NotNode",
    "ExpressionParameter",
    "IntegerLiteral",
    "StringLiteral",
    "True",
    "False",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=ba6d950d59bcd10414b00dd05310a3bf (do not edit this line) */
