/*
 * Copyright 2014 mango.jfaster.org
 *
 * The Mango Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package org.jfaster.mango.crud.buildin.factory;

import org.jfaster.mango.crud.CrudMeta;
import org.jfaster.mango.crud.buildin.builder.BuildinAddBuilder;
import org.jfaster.mango.crud.buildin.builder.AbstractBuildinBuilder;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

/**
 * 插入数据，并返回自增ID
 *
 * @author ash
 */
public class BuildinAddAndReturnGeneratedIdBuilderFactory extends AbstractBuildinBuilderFactory {

  @Override
  String expectedMethodName() {
    return "addAndReturnGeneratedId";
  }

  @Override
  Type expectedReturnType(Class<?> entityClass) {
    return long.class;
  }

  @Override
  List<Type> expectedParameterType(Class<?> entityClass, Class<?> idClass) {
    List<Type> types = new ArrayList<Type>();
    types.add(entityClass);
    return types;
  }

  @Override
  AbstractBuildinBuilder createInternalBuilder(CrudMeta cm) {
    String property4AutoGenerated = cm.getProperty4AutoGenerated();
    if (property4AutoGenerated == null) { // 没有使用 @AutoGenerated 注解，却调用生成自增主键的方法
        throw new IllegalStateException("No @AutoGenerated, but called addAndReturnGeneratedId");
    }
    return new BuildinAddBuilder(property4AutoGenerated, cm.getProperties(), cm.getColumns());
  }

}
